### ISSUE TITLE
Can't run a command

### ISSUE THREAD

**Issue by Aghits** [Ayfri/Advanced-Command-Handler#24]
Title 

Bot won't run the command

command only sends an embed message

**Comment by Ayfri** [comment]
Send the code of the command so I can search if there is any error in my code or yours.

**Comment by Aghits** [comment]
> Send the code of the command so I can search if there is any error in my code or yours.

```const { Command } = require('advanced-command-handler');
const { MessageEmbed } = require('discord.js');
module.exports = new Command({
    name: 'help',
    description: 'Show Help',
    // Optionnals :
    usage: 'hhelp',
    category: 'info',
    nsfw: false,
    guildOnly: false,
    ownerOnly: false,
    aliases: [],
    userPermissions: [],
    clientPermissions: [],
}, async(client, message, args) => {
    const testEmbed = new MessageEmbed()
    .setTitle('Help')
    .setDescription('To get a list of commands type hcommands')
    .addField('Need help?', 'Join https://discord.gg')
    message.channel.send(testEmbed);
});```

**Comment by Ayfri** [comment]
Everything seems okay, does the file is in a folder **into** your 'commands' folder ?

**Comment by Aghits** [comment]
> Everything seems okay, does the file is in a folder **into** your 'commands' folder ?
> 
> Can you send what it the output in the console when you do this :
> 
> ```js
> console.log(CommandHandler.commands.find(command) => command.name === 'help'));
> ```

It's in the commands subfolder

**Comment by Ayfri** [comment]
Can you send what it the output in the console when you do this :
```js
console.log(CommandHandler.commands.find(command) => command.name === 'help'));
```

**Comment by Aghits** [comment]
> Can you send what it the output in the console when you do this :
> 
> ```js
> console.log(CommandHandler.commands.find(command) => command.name === 'help'));
> ```

I don't think you can execute it...

**Comment by Ayfri** [comment]
I did a typo, it's `((command) =>`, not `(command) =>` ^^'

**Comment by Aghits** [comment]
Malformed arrow function parameter list

**Comment by Aghits** [comment]
Command {
  name: 'help',
  run: [AsyncFunction],
  description: 'Show Help',
  usage: 'hhelp',
  category: 'info',
  aliases: [],
  clientPermissions: [],
  userPermissions: [],
  guildOnly: false,
  ownerOnly: false,
  nsfw: false
}

**Comment by Ayfri** [comment]
It is normal, you don't have any events, remember what I said in the README :
#### This is an example, the message event is not integrated into the command handler, you have to create it yourself !
