### ISSUE TITLE
[QUESTION] Configuration

### ISSUE THREAD

**Issue by KaToRa192** [Ayfri/Advanced-Command-Handler#28]
Hello I have a question, where am I suppose to put the configuration, how do I name it or what am i suppose to do here about the configuration. And also I have install npm advanced-command-handler sooo is there a file that will create for me? if so then it doesn't
![Screenshot_7](https://user-images.githubusercontent.com/34789219/94147106-712d2900-fea7-11ea-8b3e-e94a27752b5c.jpg)

**Comment by Ayfri** [comment]
Hi !
You have to install the package using npm (or yarn/pnpm) like this :
`npm I advanced-command-handler`.

Then create a main file (the one you have to execute with node to launch the client), this is where you will configure the handler.

It should works now !

**Comment by KaToRa192** [comment]
How do i name the file btw?

**Comment by Ayfri** [comment]
You name it however you want !

**Comment by KaToRa192** [comment]
then i copy and paste this the one i just created?

const {CommandHandler} = require('advanced-command-handler');

CommandHandler.create({  
    commandsDir: 'name of the dir',
    eventsDir: 'name of the dir',
    // Optionnals :
    prefixes: ['!', 'coolPrefix '],
    owners: ['Discord IDs']
});

CommandHandler.launch({
    token: "YOUR TOKEN GOES HERE",
    // Optionnal :
    clientOptions: {
        // Client Options, see Discord.js#ClientOptions
    }
});

**Comment by Ayfri** [comment]
Exactly, then you start it with this command `node [your file]` (where `[your file]` is the name of the file).

If it doesn't works, check if you have node version 12 or plus installed

**Comment by KaToRa192** [comment]
AH ok, I found it out Thank You!

**Comment by Ayfri** [comment]
No problem !

Reopen the issue if you have other problems on how to launch the command handler 👍🏻
