### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by KaToRa192** [Ayfri/Advanced-Command-Handler#29]
Hello again, is there something wrong with the command that I don't understand. Because i tried using with prefix and it doesn't seem to respond. 
![Screenshot_7](https://user-images.githubusercontent.com/34789219/94258166-03443880-ff5f-11ea-9784-2e5b1c49947d.jpg)

**Comment by Ayfri** [comment]
You have to create yourself the message event, it's totally normal that the but is not responding.

You can get exemples of message events in my [advanced-command-handler-examples repo](https://github.com/Ayfri/advanced-command-handler-examples).

**Comment by KaToRa192** [comment]
ok thank you!

**Comment by liam-gen** [comment]
I cannot find the event message on this repo

**Comment by Ayfri** [comment]
It's now named `messageCreate`, the guide is not up-to-date for now because I don't have much time for it.

**Comment by liam-gen** [comment]
And what do I put in this event?

**Comment by Ayfri** [comment]
What do you mean ? You could [include an object as an argument to customize how you want the event to work](https://advanced-command-handler.github.io/docs/docs-release/modules/CommandHandler.html#useDefaultEvents), but there's nothing to do with the event directly.
