### ISSUE TITLE
guildCreate event is not sending messages

### ISSUE THREAD

**Issue by KaToRa192** [Ayfri/Advanced-Command-Handler#33]
so I tried guildCreate event when a bot joins a server it should send a message. i tried it multiple times and it works once but when i tried another one it wont work anymore.

![Screenshot_7](https://user-images.githubusercontent.com/34789219/97178996-451d0480-17d3-11eb-8ab2-a87cd57a2e12.jpg)

**Comment by Ayfri** [comment]
Show me your code.

**Comment by KaToRa192** [comment]
https://sourceb.in/ce95014ae5

**Comment by Ayfri** [comment]
Do you have any errors?
Because you don't check if the bot **can** send a message nor the channel exists, so there are multiple cases where your code would fail.

**Comment by KaToRa192** [comment]
there is no error i even tried using a simple bot handler it works fine with it

**Comment by Ayfri** [comment]
Oh strange, if you add a console.log (or something similar) after `channel` is declared, does it log every time?

**Comment by KaToRa192** [comment]
there is no error i even tried using a simple bot handler it works fine with it.

**Comment by KaToRa192** [comment]
nvm i fixed it I jsut have to remove 

client.on('guildCreate', guild => {

})

**Comment by Ayfri** [comment]
Oh yeah, I'm stupid, the handler makes sure that you don't need to put the `client.on`!
