### ISSUE TITLE
Certain events not working

### ISSUE THREAD

**Issue by TakeFy** [Ayfri/Advanced-Command-Handler#36]
Hi, i've added the command handler on my bot and certain events are not working such as guildMemberUpdate, guildMemberAdd, guildBanAdd. Can you help me or fix this ?

**Comment by CamilleAbella** [comment]
@TakeFy Please try to allow intents options in the Discord application page of your bot.

**Comment by TakeFy** [comment]
Yeah that's why i closed the issue my bas i fault i was already enable on dev bot token
