### ISSUE TITLE
'Channels' option in commands options

### ISSUE THREAD

**Issue by DakshNamdev** [Ayfri/Advanced-Command-Handler#38]
**Describe the solution you'd like**
Suggestion for Command Handler,
Current is
```js
{
    name: '',
    description: '',
    // Optionnals :
    usage: '',
    category: '',
    nsfw: false,
    guildOnly: false,
    ownerOnly: false,
    aliases: [],
    userPermissions: [],
    clientPermissions: [],
    cooldown: 10
}
```
I would like if there would be an `channel: (Channel-ID)`, For Channel only Specific commands

**Comment by loockeeer** [comment]
Maybe even a property `channels: ChannelResolvable[]`

So you could use a ChannelID or a Channel object from discord.js

**Comment by Ayfri** [comment]
So it should be an optional property.
But why would that be better than just adding ```if (![channels].includes(message.channel.id) return;```

**Comment by DakshNamdev** [comment]
For those who don't know much js, I knew and I was teaching a friend I
found that would be helpfull for biggeners

**Comment by Ayfri** [comment]
If you make a discord bot you have to know a little bit of javascript at least, if you want to learn javascript you don't start with a discord bot but with way simpler projects, and after you know some basics you can try to do one.

**Comment by Ayfri** [comment]
No don't close this, I want a good reason for adding it, I'm just asking you if you think that it is worth it to add it.

**Comment by DakshNamdev** [comment]
For those who don't know, For those who are too lazy to do it 😂, for those
who wants advanced command handeler to be more advanced even if it's just 1
shitty feature..
