### ISSUE TITLE
CommandHandler.launch({}) returns an error

### ISSUE THREAD

**Issue by Shamil-FD** [Ayfri/Advanced-Command-Handler#44]
**Describe the bug**
Whenever I try to start the bot, it gives out an error from the `CommandHandler.launch({})` part

This is the error I am getting:

```
CommandHandler.instance.client = new AdvancedClient_1.default(CommandHandler.instance, options.token, options.clientOptions ?? {});

				                                                                                            ^

SyntaxError: Unexpected token '?'
```

**Comment by Ayfri** [comment]
You have to have Node.js in a version above to v13.
Is it the case ?

**Comment by Shamil-FD** [comment]
I am on node v12

**Comment by Ayfri** [comment]
Upgrade to the LTS version of node, which is `14.15.3`.

**Comment by Shamil-FD** [comment]
Ok

**Comment by Ayfri** [comment]
Does it fix your error?

**Comment by Shamil-FD** [comment]
Thank you, it works! :-)
