### ISSUE TITLE
How to get client class.

### ISSUE THREAD

**Issue by TakeFy** [Ayfri/Advanced-Command-Handler#53]
Hey i'm using the command handler for 6 month now it's awesome working perfect on 500 guilds + ! But how can I get client information in the file that i iniated the command handler (index.js) in previous version it was CommandHandler.client but know it's returning _undefined_ so how can I do ?
here is an image.

![image](https://user-images.githubusercontent.com/62612084/104446923-6653ec80-559b-11eb-802e-c07f6a3a8fd9.png)

Thanks for helping me, I'm giving lot's of support.

**Comment by Ayfri** [comment]
Which version do you have ?

**Comment by TakeFy** [comment]
thanks you very much i need to upgrade all event if i upgrade and can you breifly explained what is one parameter ?

**Comment by TakeFy** [comment]
and if you can help me i've just updated to latest version.

![image](https://user-images.githubusercontent.com/62612084/104448641-bc299400-559d-11eb-835a-d3a670f2e61e.png)
I get this error

![image](https://user-images.githubusercontent.com/62612084/104448831-f6933100-559d-11eb-9a85-f599cd74590b.png)

with not clientPermission required event if i put administrator in permission it's not working and still getting this error

**Comment by Ayfri** [comment]
Okay it's a bug, I tried to fix #45 in the release but I didn't tested it haha, so the solution should be to downgrade to 2.1.1 and wait the patch I'm gonna create today ^^'

**Comment by TakeFy** [comment]
ok thanks for answering

**Comment by Ayfri** [comment]
Normally this should be fixed with the new 2.2.1 release, I tested it also ^^

**Comment by Ayfri** [comment]
Re-open this issue if it is still occurring.
