### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by TakeFy** [Ayfri/Advanced-Command-Handler#58]
Hey I was wondering if we could custom the command handler like adding some command parameter for us, and what are tag uses ?

**Comment by Ayfri** [comment]
What do you mean with `command parameters` ?

Tags are here to simplify conditional commands, when using the default message event, i.e. if you put the tag `guildOnly`, the command won't execute in DM, sending an error message.

**Comment by TakeFy** [comment]
oh ok for tag and command parameters I mean adding my own custom parameters like for example i want to restrict certain command only for top.gg voters so instead of writing code for each file, i was wondering if i could added it in command handler

**Comment by Ayfri** [comment]
You can try by extending the Command class and add your parameters, but you'll have to change types everywhere if it is in TypeScript, and it may fail with the default message event.

But !

For 3.0.0, I'll change the Command & Event system entirely, and for each command, you'll have to create a class extending the default Command class (or a custom class for special behaviour like yours), same for Events and it will be a lot much cleaner and simple do develop with this !
So my advice is to wait for 3.0.0, and use a function for your behaviour for now.

**Comment by TakeFy** [comment]
ok well thanks

**Comment by Ayfri** [comment]
Close the issue if you don't have anything else to ask about ^^
