### ISSUE TITLE
Bind & unbind client event

### ISSUE THREAD

**Issue by TakeFy** [Ayfri/Advanced-Command-Handler#59]
Hey sorry but I was wondering what does bind and unbind client event

**Comment by Ayfri** [comment]
It binds the event to the Client, if you bind an event named `message`, the `run` method will be fired when the `message` event is fired from Discord.js.

And unbind delete this behavior.

**Comment by TakeFy** [comment]
Ok thanks but how action unbin event ?

**Comment by Ayfri** [comment]
What do you mean?

**Comment by TakeFy** [comment]
I mean how to bind event and how to fire, enable  them

**Comment by Ayfri** [comment]
To bind events you execute the `bind` method, then it's automatic if you saved the event.

**Comment by TakeFy** [comment]
ok and to fire it

**Comment by Ayfri** [comment]
If it is bind to the client, it will be automatically fired.

**Comment by TakeFy** [comment]
so when bot is ready it's fired

**Comment by Ayfri** [comment]
When the event should be fired, you seem to don't understand at all the principle of events, you should read an article/book/tutorial on how they work, how and when to use these.
