### ISSUE TITLE
How can I make an reaction event?

### ISSUE THREAD

**Issue by cristiioan** [Ayfri/Advanced-Command-Handler#60]
How can I make an reaction event?

**Comment by Ayfri** [comment]
You simply create an event with the name property `messageReactionAdd`/`messageReactionRemove` etc.
You can see the list [here](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-messageReactionAdd).

**Comment by Ayfri** [comment]
Reopen the issue if you still don't understand how to do it.
