### ISSUE TITLE
Error when loading command 

### ISSUE THREAD

**Issue by TakeFy** [Ayfri/Advanced-Command-Handler#67]
Hi so i update the command handler to last version last week everything was working but since i merged update to my vps it sending this error. And I really need to have you're point of vue on that because I need to do an update today ...
What i've try : 
Duplicate the bot folder that is working : result same error
Recreate a bot with command handler a put a simple ping command to test : result working 
Put all command to the previous recreate folder : result working 
But i've try this on vps : result not working

I don't think it's an error in my code because it was all working but when i merged on vps it's not working 

![image](https://user-images.githubusercontent.com/62612084/106381228-9da60400-63b7-11eb-85e1-d6637289cda3.png)

**Comment by Ayfri** [comment]
So same error as #63... 🤔

Can you send a picture of the files & folders of your project ?

**Comment by TakeFy** [comment]
But i don't know why is not working it's big file wait i can send here sorry

**Comment by TakeFy** [comment]
i was working on local host but i merged on vps not working

**Comment by Ayfri** [comment]
No, I don't want the content of the file, I just want a screen of the folder/files list, like this (here it's not complete):
![image](https://user-images.githubusercontent.com/34159136/106383334-971e8900-63c5-11eb-9c12-89b74d9713b1.png)

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/106383940-be2a8a00-63c8-11eb-90e9-a4d02341b439.png)

**Comment by TakeFy** [comment]
dist
![image](https://user-images.githubusercontent.com/62612084/106383946-c256a780-63c8-11eb-986c-c5831c1b1fcb.png)

**Comment by TakeFy** [comment]
utls 
![image](https://user-images.githubusercontent.com/62612084/106383962-cedb0000-63c8-11eb-9812-57fe4acd464c.png)
class 
![image](https://user-images.githubusercontent.com/62612084/106383966-d4d0e100-63c8-11eb-8e24-8e157a6ee6db.png)
asset 
![image](https://user-images.githubusercontent.com/62612084/106383969-d9959500-63c8-11eb-82aa-5c1dc30b98f9.png)

**Comment by Ayfri** [comment]
I don't need the file list of the command handler but of **your** project.

**Comment by TakeFy** [comment]
oh ok

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/106384250-1c0ba180-63ca-11eb-8f48-8a919300262f.png)

**Comment by TakeFy** [comment]
![Uploading image.png…]()

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/106384263-2c238100-63ca-11eb-9c0f-04aa82af5771.png)

**Comment by Ayfri** [comment]
After some research, I think that I've found why this occurs, and it will be normally fix in the next update.

**Comment by TakeFy** [comment]
OMG thanks how do you going to release because i need it as fast as you can

**Comment by TakeFy** [comment]
?

**Comment by Ayfri** [comment]
What is it?

**Comment by TakeFy** [comment]
can you update ?

**Comment by Ayfri** [comment]
Update is out.

**Comment by TakeFy** [comment]
oh ok

**Comment by TakeFy** [comment]
so i do npm i advanced-command-handler@latest

**Comment by Ayfri** [comment]
Yeah, don't forget to remove the package in your node_modules if you're using npm v7 (node v15).

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/106387116-7b70ae00-63d8-11eb-8051-e7fcc7fd04bf.png)
Style not : (

**Comment by whoisbaby** [comment]
I got same eror as @TakeFy and i updated to 2.3.0 and it's same error.

**Comment by Ayfri** [comment]
Does the error occur on the same Command?
If yes can you send on a gist/hastebin the code?

**Comment by TakeFy** [comment]
> Does the error occur on the same Command?
> If yes can you send on a gist/hastebin the code?

no i try to delete embed builder command & it's not fixing

**Comment by TakeFy** [comment]
but i told you in localhost with new v was working

**Comment by Ayfri** [comment]
Yes, I know, but it seems that the way the command was exported (in the file) is not "compatible" with the way the CommandHandler reads and imports commands.
So I'm trying to understand why.

**Comment by TakeFy** [comment]
> Yes, I know, but it seems that the way the command was exported (in the file) is not "compatible" with the way the CommandHandler reads and imports commands.
> So I'm trying to understand why.

ok so i give u source bin already

**Comment by TakeFy** [comment]
so do you want code ?https://sourceb.in/hMTlGQhXT6

**Comment by Ayfri** [comment]
Okay, I've made a mistake, I don't need the code for this command but for the next command after embedBuilder.

**Comment by TakeFy** [comment]
https://sourceb.in/OyhHsooNMK kick

**Comment by Ayfri** [comment]
Okay, does the code is valid?
Can you verify it with a linter?
Because with only the configuration of the command I don't have any error for both in my tests.

> Note:
> There are sooo many Discord bots in the world, also in France (I'm also french so I know it ¯\_(ツ)_/¯), so your code is not "precious" nor "original", if you search `kick command discord bot` on Google/GitHub, you'll find a lot of examples. Why do I say that? If you don't know how to verify/lint a JS code, you can also send the code here, and you shouldn't think like "everyone will copy me", because there are so many `kick` command available on google that no one will copy you.

**Comment by TakeFy** [comment]
but everything was working yesterday on localhost so i don't know why it's not working and it's still  the same version my code was working yesterday on same version

**Comment by TakeFy** [comment]
https://sourceb.in/iiWf7meoi3

**Comment by Ayfri** [comment]
Mh weird, everything seems to work with me when putting dumb values, and nothing else should break this, are you really sure that the Node version is 14.x or 15.x?
To know the version of Node, execute `node --version`.

Can you send me the complete logs when launching the CommandHandler?

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/106389631-9cd79700-63e4-11eb-9c57-533035b4820d.png)

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/106389639-acef7680-63e4-11eb-8cc9-08984d45aa9e.png)

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/106389812-a9102400-63e5-11eb-8cf2-9e8646ff40ec.png)
and then on file where it's working i get this issue

**Comment by TakeFy** [comment]
even i i delete kick command same error

**Comment by TakeFy** [comment]
i've fixed oh my fking god
p

**Comment by TakeFy** [comment]
the error was a command that don't have command handler command template like a random file

**Comment by Ayfri** [comment]
I don't understand, could you explain more precisely?

**Comment by whoisbaby** [comment]
@Ayfri he say he have a random file **emoji.js** with some random text.

**Comment by TakeFy** [comment]
well let me explain you i had a random emoji.js file with nothing in it just a blank file.js so i reckon that like otehr command handler it's "querying" .js file but the file was empty so bot can't read it

**Comment by Ayfri** [comment]
Okay, I see, no problem!

**Comment by TakeFy** [comment]
but know i get this error with last version 2.30 
![image](https://user-images.githubusercontent.com/62612084/106390133-31db8f80-63e7-11eb-9534-31f60280658e.png)

**Comment by TakeFy** [comment]
so i downgrad to 2.2.2 for now

**Comment by Ayfri** [comment]
This error seems to occur when some events are not valid.
It seems that the `channelCreate` event is not valid.

**Comment by TakeFy** [comment]
channel create event is valid ^^
