### ISSUE TITLE
Bug with owner only

### ISSUE THREAD

**Issue by TakeFy** [Ayfri/Advanced-Command-Handler#68]
Hey can you put owner only back please I was currently using this feature and i don't know why it's disable. it was so useful please put it back, someone change the avatar of my bot with that

**Comment by Ayfri** [comment]
The property has just been transformed to a Tag, see how tags should works [here](https://ayfri.github.io/Advanced-Command-Handler/enums/classes_command.tag.html).

**Comment by TakeFy** [comment]
> The property has just been transformed to a Tag, see how tags should works [here](https://ayfri.github.io/Advanced-Command-Handler/enums/classes_command.tag.html).

well thanks but do you have new event message though the template ? like v1.1.1 with test bot

**Comment by Ayfri** [comment]
The default messages/commands ?
